version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgresDb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_MAX_CONNECTIONS: ${MAX_CONNECTIONS}  # Максимальное количество соединений
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    command: ["postgres", "-c", "max_connections=1000"]

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrator
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminerr
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    depends_on:
      - postgres
      - migrator
    environment:
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      BACKEND_URL: ${BACKEND_URL}
    ports:
      - "8008:8008"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge